### ISSUE TITLE
Does not even compile

### ISSUE THREAD

**Issue by amarcis** [0rangeFox/Drogon-JWT-Filter-example#1] opened 2022-03-05 13:35 UTC
Does not even compile:
error: ‘picojson_traits’ is not a member of ‘jwt’

**Comment by 0rangeFox** [comment] 2022-04-01 02:11
Hey @amarcis, sorry for the time delay, but have you been able to resolve the error yet? If not, could you please tell me what steps you followed? Thank you.

**Comment by 0rangeFox** [comment] 2022-04-24 16:23
Hey again, I know it took me a long time to answer your question, but I will close this issue, if you want to continue just reopen it. Thanks.

**Closed as completed by 0rangeFox** 2022-04-24 16:23 UTC

**Comment by amarcis** [comment] 2022-04-25 08:07
Sorry to answer late. I have not solved this problem. 
I'm using a different library for JWT, but maybe I'll try again with your tool in a while. 
Thanks

**Comment by daabtech** [comment] 2022-12-28 12:23
I have meet the same problem，in the file ”src/utils/jwt.h“,"::jwt::picojson_traits::value_type" must be a class name or a space name,but i find not "picojson_traits"in the project,thank you very much.

**Comment by 0rangeFox** [comment] 2022-12-29 03:25
> I have meet the same problem，in the file ”src/utils/jwt.h“,"::jwt::picojson_traits::value_type" must be a class name or a space name,but i find not "picojson_traits"in the project,thank you very much.

Hey, can you try to follow the steps from [README](https://github.com/0rangeFox/Drogon-JWT-Filter-example/blob/master/README.md)?

**Comment by daabtech** [comment] 2022-12-29 12:44
I did.
In file included from /home/dream/Documents/drogon-jwt/Drogon-JWT-Filter-example/src/controllers/auth/Auth.h:5,
                 from /home/dream/Documents/drogon-jwt/Drogon-JWT-Filter-example/src/controllers/auth/Auth.cc:1:
/home/dream/Documents/drogon-jwt/Drogon-JWT-Filter-example/src/utils/jwt/JWT.h:24:69: error: ‘picojson_traits’ is not a member of ‘jwt’
         static JWT generateToken(const std::map<std::string, ::jwt::picojson_traits::value_type>& claims = {}, const bool& extension = false);
                                                                     ^~~~~~~~~~~~~~~

**Comment by daabtech** [comment] 2022-12-29 12:46
/home/dream/Documents/drogon-jwt/Drogon-JWT-Filter-example/src/utils/jwt/JWT.h:24:34: error: template placeholder type ‘const map’ must be followed by a simple declarator-id
         static JWT generateToken(const std::map<std::string, ::jwt::picojson_traits::value_type>& claims = {}, const bool& extension = false);
                                  ^~~~~
In file included from /usr/include/c++/8/map:61,
                 from /home/dream/Documents/drogon-jwt/Drogon-JWT-Filter-example/libraries/drogon/lib/inc/drogon/CacheMap.h:21,
                 from /home/dream/Documents/drogon-jwt/Drogon-JWT-Filter-example/libraries/drogon/lib/inc/drogon/drogon.h:22,
                 from /home/dream/Documents/drogon-jwt/Drogon-JWT-Filter-example/src/controllers/auth/Auth.h:3,
                 from /home/dream/Documents/drogon-jwt/Drogon-JWT-Filter-example/src/controllers/auth/Auth.cc:1:
/usr/include/c++/8/bits/stl_map.h:100:11: note: ‘template<class _Key, class _Tp, class _Compare, class _Alloc> class std::map’ declared here
     class map
           ^~~

**Comment by daabtech** [comment] 2022-12-29 12:49
I tried to fellow step by step from readme,but still have the error.
My system is Deepin Linux(Based Debian).

**Comment by 0rangeFox** [comment] 2022-12-29 20:48
> I tried to fellow step by step from readme,but still have the error.
> My system is Deepin Linux(Based Debian).

Maybe it's missing some dependencies, did you tried to install the [PicoJSON](https://packages.debian.org/unstable/picojson-dev) package? Also, did you followed the [Drogon installation](https://github.com/drogonframework/drogon/wiki/ENG-02-Installation)?

**Comment by daabtech** [comment] 2022-12-30 00:49
PicoJson is a head only file under the jwt-cpp folder,no dependencies missing.What did "picojson_traits" mean,i cannot find in the jwt.

**Comment by 0rangeFox** [comment] 2022-12-30 02:30
Alright I see, maybe it's need an update itself on the code, later I will check it.

**Comment by daabtech** [comment] 2022-12-30 02:34
Thank you very much.

**Comment by 0rangeFox** [comment] 2022-12-30 02:41
I just cloned again the project and compiled it, it's actually is running without any problems. So I'm pretty the problem is on your side. Can you tell me step a step how did you setup this?

**Comment by daabtech** [comment] 2022-12-30 02:50
1、git clone Drogon-JWT-Filter-example.
2、git clone drogon and install drogon dependencies(trantor).
3、git clone jwt-cpp.
4、cd build
5、cmake ..

**Comment by daabtech** [comment] 2022-12-30 02:53
I clone the newest version of drongon(1.8.2) by hand.

**Comment by daabtech** [comment] 2022-12-30 04:33
Actually，i could not understand the mean of  "::jwt::picojson_traits::value_type",there is no member of jwt.

**Comment by daabtech** [comment] 2022-12-30 08:46
At last，i found the reason, i cloned the newest version of jwt-cpp by hand,i am sorry,thank you.
